<#
.SYNOPSIS
    Pack MCPE 0.6.1 game data + runtime DLLs into Win32 resources so the game
    can be compiled into a single self-contained .exe.

.DESCRIPTION
    Generates, under handheld\project\win32\pack\:
      data.bin       - custom archive (MCPEPACK1) of handheld\data
      dll\           - the four runtime DLLs (libEGL, libgles_cm, libpng12, zlib1)
      packhash.txt   - content hash used to invalidate the per-user cache
      resources.rc   - resource script linking the above into the executable
#>
$ErrorActionPreference = 'Stop'

$ROOT     = Split-Path -Parent $PSScriptRoot
$DATA_SRC = Join-Path $ROOT 'handheld\data'
$LIB_BIN  = Join-Path $ROOT 'handheld\lib\bin'
$PACK_DIR = Join-Path $ROOT 'handheld\project\win32\pack'
$ICON_SRC = Join-Path $ROOT 'handheld\project\android\res\drawable-hdpi\icon.png'
$DLLS     = @('libEGL.dll', 'libgles_cm.dll', 'libpng12.dll', 'zlib1.dll')

New-Item -ItemType Directory -Force -Path $PACK_DIR | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $PACK_DIR 'dll') | Out-Null

if (-not (Test-Path $DATA_SRC)) {
    Write-Error "data folder not found: $DATA_SRC"
}

# ---- 0. Game icon (wrap the Android launcher PNG into an .ico) ----
if (Test-Path $ICON_SRC) {
    $png = [System.IO.File]::ReadAllBytes($ICON_SRC)
    $ms = New-Object System.IO.MemoryStream
    $bw = New-Object System.IO.BinaryWriter($ms)
    $bw.Write([uint16]0)          # reserved
    $bw.Write([uint16]1)          # type: icon
    $bw.Write([uint16]1)          # count
    $bw.Write([byte]$png[16])     # width
    $bw.Write([byte]$png[20])     # height
    $bw.Write([byte]0)            # palette
    $bw.Write([byte]0)            # reserved
    $bw.Write([uint16]1)          # planes
    $bw.Write([uint16]32)         # bpp
    $bw.Write([uint32]$png.Length)
    $bw.Write([uint32]22)         # data offset
    $bw.Write($png)
    $bw.Flush()
    [System.IO.File]::WriteAllBytes((Join-Path $PACK_DIR 'icon.ico'), $ms.ToArray())
    $bw.Dispose()
    $ms.Dispose()
}

# ---- 1. Build the MCPEPACK1 archive of the data folder ----
$entries = Get-ChildItem $DATA_SRC -Recurse -File | Sort-Object FullName
$ms = New-Object System.IO.MemoryStream
$bw = New-Object System.IO.BinaryWriter($ms)
$ascii = [System.Text.Encoding]::ASCII
$utf8  = [System.Text.Encoding]::UTF8

$bw.Write($ascii.GetBytes('MCPEPACK'))
$bw.Write([uint32]$entries.Count)
foreach ($e in $entries) {
    $rel = $e.FullName.Substring($DATA_SRC.Length + 1).Replace('\', '/')
    $data = [System.IO.File]::ReadAllBytes($e.FullName)
    $relBytes = $utf8.GetBytes($rel)
    $bw.Write([uint32]$relBytes.Length)
    $bw.Write($relBytes)
    $bw.Write([uint32]$data.Length)
    $bw.Write($data)
}
$bw.Flush()
$packBytes = $ms.ToArray()
$bw.Dispose()
$ms.Dispose()

[System.IO.File]::WriteAllBytes((Join-Path $PACK_DIR 'data.bin'), $packBytes)

# ---- 2. Copy the runtime DLLs ----
$dllBytes = @{}
foreach ($name in $DLLS) {
    $src = Join-Path $LIB_BIN $name
    if (-not (Test-Path $src)) {
        Write-Error "missing DLL: $src"
    }
    $data = [System.IO.File]::ReadAllBytes($src)
    [System.IO.File]::WriteAllBytes((Join-Path (Join-Path $PACK_DIR 'dll') $name), $data)
    $dllBytes[$name] = $data
}

# ---- 3. Content hash (cache invalidation) ----
$sha = [System.Security.Cryptography.SHA256]::Create()
$h = $sha.ComputeHash($packBytes)
foreach ($name in $DLLS) {
    $nameBytes = $ascii.GetBytes($name)
    $tmp = New-Object byte[] ($h.Length + $nameBytes.Length + $dllBytes[$name].Length)
    [System.Buffer]::BlockCopy($h, 0, $tmp, 0, $h.Length)
    [System.Buffer]::BlockCopy($nameBytes, 0, $tmp, $h.Length, $nameBytes.Length)
    [System.Buffer]::BlockCopy($dllBytes[$name], 0, $tmp, $h.Length + $nameBytes.Length, $dllBytes[$name].Length)
    $h = $sha.ComputeHash($tmp)
}
$sha.Dispose()
$hashHex = ([System.BitConverter]::ToString($h)).Replace('-', '').ToLowerInvariant().Substring(0, 24)
[System.IO.File]::WriteAllText((Join-Path $PACK_DIR 'packhash.txt'), $hashHex, $ascii)

# ---- 4. Resource script ----
$rc = @'
// Auto-generated by tools/pack_resources.ps1 - do not edit
#define IDR_DATAPACK  101
#define IDR_DLL_EGL   102
#define IDR_DLL_GLES  103
#define IDR_DLL_PNG   104
#define IDR_DLL_ZLIB  105
#define IDR_PACKHASH  106
#define IDI_APP       107

IDR_DATAPACK  RCDATA  "data.bin"
IDR_DLL_EGL   RCDATA  "dll/libEGL.dll"
IDR_DLL_GLES  RCDATA  "dll/libgles_cm.dll"
IDR_DLL_PNG   RCDATA  "dll/libpng12.dll"
IDR_DLL_ZLIB  RCDATA  "dll/zlib1.dll"
IDR_PACKHASH  RCDATA  "packhash.txt"

IDI_APP       ICON    "icon.ico"
'@
[System.IO.File]::WriteAllText((Join-Path $PACK_DIR 'resources.rc'), $rc, $ascii)

$dllTotal = 0
foreach ($name in $DLLS) { $dllTotal += $dllBytes[$name].Length }
Write-Host ("Packed {0} data files ({1} bytes), {2} bytes of DLLs, hash {3}" -f `
    $entries.Count, $packBytes.Length, $dllTotal, $hashHex)
